- name: Ensure mkfs.btrfs is there
  apt:
    name: btrfs-progs
    state: present
  when: ansible_distribution == "Debian"

# Is this indempotent?
- name: Create btrfs on block device
  command: mkfs.btrfs "{{ src }}"

- name: Mount filesystem
  mount:
    src: "{{ src }}"
    path: "{{ path }}"
    fstype: btrfs
    opts: relatime
    state: mounted
